name: Deploy to Azure Kubernetes Service (AKS)

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI/CD - Build & Push React App"]
    types:
      - completed

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_TOKEN }}" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
