  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write   
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --admin --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/react-app react-app=ayushmukherjee22b/react-app:${{ needs.build-and-push.outputs.image_tag }}
