name: Deploy to Azure Kubernetes Service (AKS)

on:
  workflow_run:
    workflows: ["CI/CD - Build & Push React App"]
    types:
      - completed

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --admin --overwrite-existing

    - name: Download Image Tag from Build Workflow
      uses: actions/download-artifact@v4
      with:
        name: image-tag

    - name: Read Image Tag
      run: echo "IMAGE_TAG=$(cat image-tag.txt)" >> $GITHUB_ENV

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/react-app react-app=ayushmukherjee221b/react-app:$IMAGE_TAG
