  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_image_tag.outputs.image_tag }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Commit SHA
      id: set_image_tag
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Debug: Print IMAGE_TAG
      run: echo "IMAGE_TAG=${{ env.IMAGE_TAG }}"

    - name: Build and Push Docker image
      run: |
        docker build -t ayushmukherjee221b/react-app:${{ env.IMAGE_TAG }} .
        docker push ayushmukherjee221b/react-app:${{ env.IMAGE_TAG }}

    - name: Logout from Docker Hub
      run: docker logout
