name: CI/CD - Build & Push React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Commit SHA
      id: set_image_tag
      run: |
        IMAGE_TAG=$(git rev-parse --short HEAD)
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Build and Push Docker image
      run: |
        docker build -t ayushmukherjee221b/react-app:$IMAGE_TAG .
        docker push ayushmukherjee221b/react-app:$IMAGE_TAG

    - name: Logout from Docker Hub
      run: docker logout

    - name: Save Image Tag for Deployment
      run: echo "$IMAGE_TAG" > image-tag.txt

    - name: Upload Image Tag as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: image-tag.txt
